### ISSUE TITLE
click-odoo-makepot : blocking error when the i18n folder already contains some .po files

### ISSUE THREAD

**Issue by clementmbr** [acsone/click-odoo-contrib#109]
Actually when I try to run `click-odoo-makepot -m my_module` it only works when there is no existing .po files. Where there is already one .po file, I get this error :

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/click_odoo/env_options.py", line 211, in _invoke
    return self.org_invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click_odoo_contrib/makepot.py", line 181, in main
    purge_old_translations,
  File "/usr/local/lib/python3.7/dist-packages/click_odoo_contrib/makepot.py", line 83, in export_pot
    ["msgmerge", "--quiet", lang_filepath, pot_filepath]
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msgmerge': 'msgmerge'
Error: [Errno 2] No such file or directory: 'msgmerge': 'msgmerge'
```

I tried with Odoo v14.
If I run `click-odoo-makepot -m my_module --no-msgmerge` I get the same error.

I never used this `subprocess` package so I'm afraid I won't be a good contributor for this... but I loved the general idea of these click-odoo-contrib tools !

Thanks!

**Comment by sbidoul** [comment]
The msgmerge program is missing on your system. You must install it. It is part of the gettext package.

**Comment by clementmbr** [comment]
It was it! Works perfectly. Thanks for the answer and sorry for the silly question...
