### ISSUE TITLE
[>1.8.0] click-odoo-update , raising error when updating checksum

### ISSUE THREAD

**Issue by GSLabIt** [acsone/click-odoo-contrib#82]
Getting following error, somehow connection get closed earlier than expected, any hint?

```
2020-10-25 19:57:36,957 19976 ERROR dbname odoo.sql_db: bad query: SELECT pg_advisory_unlock(39646140878765077::bigint)
ERROR: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

2020-10-25 19:57:36,957 19976 ERROR karedesign click_odoo.env_options: exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/click_odoo_contrib/update.py", line 244, in _update_db
    ignore_addons,
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/click_odoo_contrib/_dbutils.py", line 63, in advisory_lock
    cr.execute("SELECT pg_advisory_unlock(%s::bigint)", (lock_id,))
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/click_odoo/env_options.py", line 211, in _invoke
    database=database, rollback=rollback, ctx=ctx
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/click_odoo_contrib/update.py", line 272, in OdooEnvironmentWithUpdate
    ignore_addons,
  File "/usr/local/lib/python3.6/dist-packages/click_odoo_contrib/update.py", line 244, in _update_db
    ignore_addons,
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 401, in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 285, in close
    return self._close(False)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 315, in _close
    self._cnx.rollback()
psycopg2.InterfaceError: connection already closed
```

**Comment by GSLabIt** [comment]
@sbidoul any hint on this?

**Comment by sbidoul** [comment]
I've never observed this. You could try with a `try/except: pass` around the `pg_advisory_unlock` statement in case that is masking another error.

**Comment by GSLabIt** [comment]
@sbidoul will try, it seems a problem after this commit: 

https://github.com/acsone/click-odoo-contrib/commit/2854ed2f6b9cef8e68d4597d7d67549e73mod38aebc#diff-b2b4207d23e77e4de5c1e894248403eba6af527e3369fac82a1385f1e1ef33ec

moving lock_id out of the init, could that be an issue? guessing

**Comment by GSLabIt** [comment]
> I've never observed this. You could try with a `try/except: pass` around the `pg_advisory_unlock` statement in case that is masking another error.

```
2020-10-26 18:39:24,090 7068 ERROR digitosrl odoo.sql_db: bad query: SELECT pg_advisory_unlock(69528899230690759::bigint)
ERROR: terminating connection due to idle-in-transaction timeout
ERROR:  server conn crashed?
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

2020-10-26 18:39:24,091 7068 ERROR digitosrl click_odoo.env_options: exception
Traceback (most recent call last):
  File "/opt/odoo/.local/lib/python3.6/site-packages/click_odoo/env_options.py", line 211, in _invoke
    database=database, rollback=rollback, ctx=ctx
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/click_odoo_contrib/update.py", line 272, in OdooEnvironmentWithUpdate
    ignore_addons,
  File "/usr/local/lib/python3.6/dist-packages/click_odoo_contrib/update.py", line 244, in _update_db
    ignore_addons,
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 400, in __exit__
    self.commit()
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 372, in commit
    result = self._cnx.commit()
psycopg2.InterfaceError: connection already closed

```

**Comment by GSLabIt** [comment]
Double checked and seems related to pgbouncer even if `idle-in-transaction` is not used. Any hint from your side?

**Comment by GSLabIt** [comment]
@sbidoul, we found the issue, it is related to postgresql config: `idle_in_transaction_session_timeout`. In our config is set to 60 sec; if db take more time to update it ends with the error.
